version: "3.9"

services:  
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwe"
    ports:
      - 5436:5432
  nats:
    image: "nats-streaming:latest"
    restart: "always"
    ports:
      - 4224:4222